# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ecommerce MVP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ecommerce MVP
  pod 'NotificationBannerSwift'

  target 'Ecommerce MVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ecommerce MVPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
